/*!
 * @file
 * @brief
 *
 * Copyright GE Appliances - Confidential - All rights reserved.
 */

#ifndef CAPTOUCHPLUGINCONFIGURATION_H
#define CAPTOUCHPLUGINCONFIGURATION_H

#include "SystemErds.h"
#include "Reset.h"

// Configuration generated by E2 Studio
#include "qe_config01.h"

#define CapTouchConfigName CONFIG01

enum
{
   // Nominal poll/scan rate
   CapTouchPollPeriodMsec = 5,

   // Diagnostics checks for all safety critical keys are performed on this period
   // with individual steps taken on CapTouchPollPeriodMsec
   // If it takes longer than this to complete a diagnostics check then we assume
   // the worst and reset
   CapTouchDiagnosticsPeriodMsec = 1000,

   // The number of consecutive CTSU diagnostics failures for a given safety
   // critical key before we throw in the towel and reset
   CapTouchDiagnosticsConsecutiveFailureLimit = 30,

   CapTouchTimerModuleErd = Erd_TimerModule,
   CapTouchResultErd = Erd_KeyState,

   // This can be set to Erd_Invalid to disable writing the corresponding value
   CapTouchDiagnosticsResultsErd = Erd_CapTouchDiagnosticsResult
};

enum
{
   // Period at which debug data is updated when the debug plugin is enabled
   CapTouchDebugPollPeriodMsec = 100,

   // These can be set to Erd_Invalid to disable writing the corresponding value
   CapTouchDebugRawCountsErd = Erd_CapTouchDebugRawCounts,
   CapTouchDebugCountsErd = Erd_CapTouchDebugCounts,
   CapTouchDebugDeltasErd = Erd_CapTouchDebugDeltas,
};

typedef KeyState_t CapTouchState_t;

#define CapTouchSystemReset() Reset()

#include "CapTouchKeys.h"

#endif
