
local enum = require 'lua-common'.utilities.enum

return enum({
  Erd_LeftSideFreshFoodDoorStatus = 0xF0A0,
  Erd_ConvertibleCompartmentDoorStatus = 0xF0A2,
  Erd_RightSideFreshFoodDoorStatus = 0xF0A8,
  Erd_LeftSideFreezerDoorStatus = 0xF0A9,
  Erd_BottomFreezerDrawerStatus = 0xF0AB,
  
  Erd_IceMaker0_MoldThermistor_AdcCount = 0xF0B0,
  Erd_IceMaker1_MoldThermistor_AdcCount = 0xF0B1,
  Erd_IceMaker2_MoldThermistor_AdcCount = 0xF0BB,
  Erd_IceMakerBoxThermistor_AdcCount = 0xF0B2,
  Erd_FreshFoodThermistor_AdcCount = 0xF0B3,
  Erd_FreezerThermistor_AdcCount = 0xF0B4,
  Erd_FreshFoodEvapThermistor_AdcCount = 0xF0B5,
  Erd_FreezerEvapThermistor_AdcCount = 0xF0B6,
  Erd_ConvertibleCompartmentCabinetThermistor_AdcCount = 0xF0B7,
  Erd_AmbientThermistor_AdcCount = 0xF0B8,
  Erd_AmbientHumidity_AdcCount = 0xF0B9,
  Erd_ConvertibleCompartmentEvapThermistor_AdcCount = 0xF0BA,

  Erd_IceMaker0_RakeMotorRelay = 0xF509,
  Erd_IceMaker1_RakeMotorRelay = 0xF41A,
  Erd_IceMaker2_RakeMotorRelay = 0xF41B,
  Erd_CompressorRelay = 0xF503,
  Erd_FreezerDefrostHeaterRelay = 0xF505,
  Erd_FreshFoodDefrostHeaterRelay = 0xF50F,
  Erd_ConvertibleCompartmentDefrostHeaterRelay = 0xF510,
  Erd_IceMaker0_WaterValveRelay = 0xF507,
  Erd_IceMaker1_WaterValveRelay = 0xF50E,
  Erd_IceMaker2_WaterValveRelay = 0xF544,
  Erd_IceMaker0_HeaterRelay = 0xF508,
  Erd_IceMaker1_HeaterRelay = 0xF545,
  Erd_IceMaker2_HeaterRelay = 0xF542,
  Erd_DispenserValveRelay = 0xF50C,
  Erd_IsolationValveRelay = 0xF50D,

  Erd_IceMaker0_FillTubeHeater = 0xF504,
  Erd_IceMaker1_FillTubeHeater = 0xF512,
  Erd_IceMaker2_FillTubeHeater = 0xF513,
  Erd_FreshFoodDamperHeater = 0xF506,
  Erd_ConvertibleCompartmentDamperHeater = 0xF511,
  
  Erd_IceMaker0_FeelerArmPosition = 0xF151,
  Erd_IceMaker1_FeelerArmPosition = 0xF1B1,
  Erd_IceMaker2_FeelerArmPosition = 0xF1B2,
  Erd_IceMaker0_RakePosition = 0xF156,
  Erd_IceMaker1_RakePosition = 0xF14E,
  Erd_IceMaker2_RakePosition = 0xF14F,

  Erd_FreshFoodBackWallLight_RampingPwm = 0xF55B,
  Erd_FreshFoodTopLight_RampingPwm = 0xF55C,
  Erd_FreezerTopLight_RampingPwm = 0xF55D,
  Erd_FreezerBackWallLight_RampingPwm = 0xF55F,
  Erd_CondenserFan_Pwm = 0xF51A,
  Erd_IceCabinetFan_Pwm = 0xF51B,
  Erd_ConvertibleCompartmentFan_Pwm = 0xF51C,
  Erd_DeliFan_Pwm = 0xF51D,
  Erd_FreezerEvapFan_Pwm = 0xF51E,
  Erd_FreshFoodEvapFan_Pwm = 0xF51F,

  Erd_CondenserFan_InputCaptureTime = 0xF53A,
  Erd_IceCabinetFan_InputCaptureTime = 0xF53B,
  Erd_ConvertibleCompartmentFan_InputCaptureTime = 0xF53C,
  Erd_DeliFan_InputCaptureTime = 0xF53D,
  Erd_FreezerEvapFan_InputCaptureTime = 0xF53E,
  Erd_FreshFoodEvapFan_InputCaptureTime = 0xF53F,
  Erd_AluminumIceMakerRake_InputCaptureTime = 0xF540,
  Erd_FlowMeter_InputCaptureCount = 0xF541,

  Erd_FreshFoodDamperStepperMotorDriveEnable = 0xF54F,
  Erd_TwistIceMakerMotorDriveEnable = 0xF550,
})
