/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "CapSense.h"
#include "CapSense_Control.h"
#include "CapSense_Filter.h"
#include "CapSense_Processing.h"
#include "CapSense_Sensing.h"
#include "CapSense_Structure.h"
#include "CapSense_Tuner.h"
#include "CapSense_Configuration.h"
#include "CapSense_SensingCSX_LL.h"
#include "CapSense_RegisterMap.h"
#include "CapSense_SelfTest.h"
#include "Gea3.h"
#include "Gea3_SPI_UART.h"
#include "Gea3_PINS.h"
#include "Gea3_SPI_UART_PVT.h"
#include "Gea3_PVT.h"
#include "Gea3_BOOT.h"
#include "CapSense_ISR.h"
#include "Gea3_SCBCLK.h"
#include "Gea3_tx.h"
#include "Gea3_tx_aliases.h"
#include "Gea3_SCB_IRQ.h"
#include "Gea3_rx.h"
#include "Gea3_rx_aliases.h"
#include "cy_em_eeprom.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "core_cm0plus_psoc4.h"
#include "CyLFClk.h"

/*[]*/

