name: pull request comment run integration tests

on:
  issue_comment:
    types: [created, edited, deleted]

jobs:
  setup:
    uses: geappliances/skynet.workflow/.github/workflows/setup-workflow.yml@v1
    secrets: inherit
    permissions:
      id-token: write
      contents: read
    with:
      artifact-retention-policy: number 50

  linux-tdd-with-integration:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/integration_tests') }}
    uses: geappliances/skynet.workflow/.github/workflows/build-workflow.yml@v1
    needs: setup
    secrets: inherit
    permissions:
      id-token: write
      contents: read
    with:
      job-name: linux-tdd-with-integration
      script: tdd
      runs-on: skynet-linux-x64

  email:
    if: ${{ (cancelled() || failure()) && github.event_name != 'pull_request' }}
    uses: geappliances/skynet.workflow/.github/workflows/email-workflow.yml@v1
    needs: [linux-tdd-with-integration]
    secrets: inherit
    permissions:
      id-token: write
      contents: read
    with:
      recipients: kira.hartlage@geappliances.com, jose.padron@geappliances.com, leonardo.falconizzi@geappliances.com
      status: Failure
