name: build

on:
  push:
    branches:
      - main
      - develop

  pull_request:

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  setup:
    uses: geappliances/skynet.workflow/.github/workflows/setup-workflow.yml@v1
    secrets: inherit
    permissions:
      id-token: write
      contents: read
    with:
      artifact-retention-policy: number 50

  linux-tdd:
    uses: geappliances/skynet.workflow/.github/workflows/build-workflow.yml@v1
    needs: setup
    secrets: inherit
    permissions:
      id-token: write
      contents: read
    with:
      job-name: linux-tdd
      script: tdd
      runs-on: skynet-linux-x64

  linux-integration:
    if: ${{ github.event_name == 'pull_request' }}
    uses: geappliances/skynet.workflow/.github/workflows/build-workflow.yml@v1
    needs: setup
    secrets: inherit
    permissions:
      id-token: write
      contents: read
    with:
      job-name: linux-tdd
      script: integration.sh
      runs-on: skynet-linux-x64

  linux-build:
    uses: geappliances/skynet.workflow/.github/workflows/build-workflow.yml@v1
    needs: setup
    secrets: inherit
    permissions:
      id-token: write
      contents: read
    with:
      job-name: linux-build
      script: build_all
      runs-on: skynet-linux-x64

  macos-tdd:
    uses: geappliances/skynet.workflow/.github/workflows/build-workflow.yml@v1
    needs: setup
    secrets: inherit
    permissions:
      id-token: write
      contents: read
    with:
      job-name: macos-tdd
      script: tdd
      runs-on: skynet-macos-generic

  parametric-linux-tdd:
    uses: geappliances/skynet.workflow/.github/workflows/build-workflow.yml@v1
    needs: setup
    secrets: inherit
    permissions:
      id-token: write
      contents: read
    with:
      job-name: parametric-linux-tdd
      script: parametric_tdd
      runs-on: skynet-linux-x64

  parametric-macos-tdd:
    uses: geappliances/skynet.workflow/.github/workflows/build-workflow.yml@v1
    needs: setup
    secrets: inherit
    permissions:
      id-token: write
      contents: read
    with:
      job-name: parametric-macos-tdd
      script: parametric_tdd
      runs-on: skynet-macos-generic

  update-parametric-repo:
    if: ${{ github.ref_name == 'develop' }}
    needs: [macos-tdd, linux-build, parametric-linux-tdd, parametric-macos-tdd]
    uses: geappliances/skynet.repository-dispatch/.github/workflows/repository-dispatch.yml@v1
    secrets: inherit
    with:
      repo: refrigeration.rockhopper-parametric
      event-type: mainboard-updated

  email:
    if: ${{ (cancelled() || failure()) && github.event_name != 'pull_request' }}
    uses: geappliances/skynet.workflow/.github/workflows/email-workflow.yml@v1
    needs: [macos-tdd, linux-build, linux-tdd, parametric-linux-tdd, parametric-macos-tdd]
    secrets: inherit
    permissions:
      id-token: write
      contents: read
    with:
      recipients: ReferSoftwareSkynetNotification@geappliances.com
      status: Failure
